### ISSUE TITLE
Add HighCoin (HIGHT)

### ISSUE THREAD

**Issue by Rikzans** [atomiclabs/cryptocurrency-icons#144]
Hi.
I would like to request about adding HighCoin (HIGHT) logo on Delta app.
What you need?
Thanks

**Comment by lukechilds** [comment]
Hi @Rikzans,

If you want to add your icon to this collection please attach a vectorised source file of your logo and we'll create an icon for it.

However, regarding Delta, I believe [they maintain their own fork](https://github.com/hyperdexapp/cryptocurrency-icons/issues/136#issuecomment-396166974) of this repo. I'm not sure if they will merge changes in from here or if you need to contact them directly.

//cc @svenlombaert

**Comment by svenlombaert** [comment]
We maintain our own fork because we only use the white and color svg. We also don't need the 'icon' variant (the one that looks like a badge). We keep our fork up to date with this repository though, so coins added here will show up in Delta as well.

If there was a way we could merge our changes back to this repo, we would be happy to do this. We added quite some coins that were not included here, but as said before, only the white and colored svg. It's simply because of time constraints and unclear contributing guidelines (and slow updates from the previous maintainer), we chose for this route.

**Comment by c1xx** [comment]
@svenlombaert means If I want to add icons for my coin BitCloud should I send you the icons?

**Comment by lukechilds** [comment]
@c1xx No, if you add the source files here we will add it and Delta can merge our changes into their fork.

@svenlombaert That would be great, if you guys get the time it would be awesome if you could submit a PR with your changes, even if they're only white and colour variants. Should be pretty straight forward for us to create the other variants from that.

Also, just FYI, we've published on npm now. Not sure what your current workflow is but you can now include this with just `npm install cryptocurrency-icons`.

Obviously it's up to you and whatever suits your workflow best, but it would be great if we could consolidate both our efforts on this. Happy to add you as a maintainer if you're worried about slow responses on our end hindering your development. No worries either way 👍

**Comment by svenlombaert** [comment]
I'll check (soonish) to make a PR with the coins we have in our fork, that aren't included here. That could work perfectly for now 👍 

If there's some tools available to create all the variants, we'd be happy to take it up in our workflow!

**Comment by lukechilds** [comment]
Awesome!

No immediate rush, we are super busy trying to get HyperDEX shipped right now so not sure exactly when I can get round to it.

**Comment by sindresorhus** [comment]
I found an SVG version of the logo here: https://highcoin.xyz/assets/img/logos/logo.svg

Attached here in case it disappears: [logo.svg.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2298310/logo.svg.zip)
