### ISSUE TITLE
Add MEMO Token (MEMO)

### ISSUE THREAD

**Issue by Telesfor1** [atomiclabs/cryptocurrency-icons#290]
Currency name: MEMO Token
Symbol: MEMO
Website: https://memo.cash
Theme color: #548D1D
Logo (SVG): https://whotipped.it/img/memo-token.svg

**Comment by sindresorhus** [comment]
I'm sorry, but there are no design elements we can use in what you've provided. We need some kind symbol for the icon, not text.

**Comment by sindresorhus** [comment]
Can you link to the CMC page for MEMO Token?

**Comment by Telesfor1** [comment]
MEMO is a SLP token (like WNT token) not listed on CMC 

PNG-Icon you can download here:
https://whotipped.it/img/memo-token.png
SVG-Icon you can download here:
https://whotipped.it/img/memo-token.svg

PNG-Icon I uploaded below:
![memo-token](https://user-images.githubusercontent.com/46196477/56294001-76227080-612a-11e9-8877-54b6617e790c.png)

**Comment by sindresorhus** [comment]
My comment https://github.com/atomiclabs/cryptocurrency-icons/issues/290#issuecomment-474833399 still stands.

**Comment by Telesfor1** [comment]
Sorry, but I don't understand what kind of symbol do you mean. I uploaded a png-Icon and linked a svg-Icon and png-Icon. What else do I have to do?

**Comment by lukechilds** [comment]
@Telesfor1 The issue is that you don't have a logo, you just uploaded an image of a circle with the name of your token on it.

If you get a proper logo designed then we can create an icon from it.

Also, are you aware this repo is unrelated to Badger Wallet? They forked our repo and left a few links in pointing over here, so we've had a few people with SLP tokens requesting an icon here when they want an icon added to Badger Wallet.

If you're looking to get your icon included in Badger Wallet then this is the correct place: https://github.com/Bitcoin-com/bch-token-icons
