### ISSUE TITLE
Add Compound cTokens

### ISSUE THREAD

**Issue by torreyatcitty** [atomiclabs/cryptocurrency-icons#304]
This is issue is to add icons for all the current Compound cTokens.
There are 6 tokens currently.

Currency name: Compound Basic Attention Token
Symbol: cBAT

Currency name: Compound Dai
Symbol: cDAI

Currency name: Compound Ether
Symbol: cETH

Currency name: Compound Augur
Symbol: cREP

Currency name: Compound USD Coin
Symbol: cUSDC

Currency name: Compound 0x
Symbol: cZRX

For all tokens:
Website: https://compound.finance/
Theme color: #27D4A2
Logos (SVG): [cToken-Assets.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3213821/cToken-Assets.zip)

Our preference is for users who show color icons to use the two tone icons wherever possible to ensure consistent branding across all products integrating compound.

**Comment by lukechilds** [comment]
Hi, thanks for opening the issue.

I don't think we can support this. If we support this it's a slippery slope, many other projects building their own tokens based on other tokens may want to be added to this icon pack too.

I think it makes more sense for this icon pack to focus on "real" currencies. If you have a project where you need your own icons based on the icons from other currencies, it would make more sense for that project to create their own icon pack based on ours. Rather than us having to support every single project that wants to do that.

**Comment by jflatow** [comment]
What's the definition of a "real" currency?

**Comment by lukechilds** [comment]
Pretty loose hence the air quotes.

But I guess in the context of this project something along the lines of "An original cryptocurrency with a non-negligible market cap or user base."

I don't really understand what cTokens are but it seems like you are just re-issuing existing tokens under a token on your own platform, which I don't think really fits our criteria.

I would suggest you either:

**A:** Use the original token icons provided by this project for cTokens.
**B:** If that isn't adequate for your project, create your own icons for your cTokens. You're more than welcome to use our open source icons as a base.

We're an open source project with limited resources. You're a commercial company that I assume is intending to make a profit.

We can't justify giving out free design services to any company that wants to build something with tokens. Hopefully you can understand that.

**Comment by jflatow** [comment]
@lukechilds Thanks for your response and for your commitment to open source. I appreciate your concerns but I'm not sure you are assessing the project fairly.

The source code is open and verified on Etherscan, e.g. for cDAI: https://etherscan.io/address/0xf5dce57282a584d2746faf1593d3121fcac444dc#contracts. Etherscan also shows the proper icons: https://etherscan.io/token/0xf5dce57282a584d2746faf1593d3121fcac444dc

cDAI/ETH is currently the 8th largest market on Uniswap. The Uniswap market was created by the community (actually, from a suggestion on Twitter https://twitter.com/VitalikButerin/status/1133188901508648960). cTokens have been listed on multiple exchanges and distributed exchanges.

The cToken Ethereum contracts are currently the second largest (after Maker) in #defi (according to https://defipulse.com). Compound the company has a strong commitment to openness and is dedicated to freedom, software or otherwise. It is a notable part of the open finance movement.

Please help cToken holders around the world enjoy the cToken icons in your project too :)

**Comment by lukechilds** [comment]
Thanks, could you also give me a succinct explanation of how cTokens differ from normal tokens?

e.g, what actually is cDAI in relation to DAI? And how does Compound the company fit into all this?

**Comment by jflatow** [comment]
cDAI > DAI, it earns interest so it strictly increases in value relative to the underlying asset (DAI for cDAI). Initially you could get 50 cDAI for a DAI, eventually 1 cDAI will be worth 1 DAI, and then one day even more. But that will take a long time.

cTokens tokenize the supply balance of the Compound money market. Interest accrues from people borrowing from the protocol, and it is earned by the token holders for supplying liquidity to borrowers.
Compound built cTokens and released them to the community as a building block for open finance. It is a venture-backed company, so making money is not yet in the picture. Half the engineering team is actually on this thread :)

**Comment by jflatow** [comment]
What do you say @lukechilds, can you help us out? Or what should we do to re-open the PR and prove that cTokens are "real"? :)
